name: 'Hello World'
description: 'Greet someone and record the time'

on: 
  push:
    branches:
      main

jobs:
  test-action:
    - name: Check out repository code
    uses: actions/checkout@v2
    run: |
      ls -la
      echo "lalala"
