name: 'Hello World'

concurrency: prod

on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Check files
      run: |
        ls -la
        echo "lalala"
        
  deployment:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo "Deploy"
